fix offset-by-one (#3)
* h26x-extractor: add a simple parsing test

Needed to refactor the parser constructor in order to allow testing
binary blobs.

Tested:

Before the AUD fix patch:

```
$ ./tests/simple_parsing.py

========================================================================================================

NALU bytepos: [0, 5]
NALU offset:  0 Bytes
NALU length:  6 Bytes (including start code)
NALU type:  9 (Access unit delimiter)
NALU bytes: 0x000000010910
NALU RBSP:

E
======================================================================
ERROR: testAUDParser (__main__.ParsingTest)
Simple AUD parsing.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./tests/simple_parsing.py", line 17, in testAUDParser
    ex.parse()
  File "/usr/local/lib/python3.7/site-packages/h26x_extractor-0.3-py3.7.egg/h26x_extractor/h26x_parser.py", line 209, in parse
    aud = nalutypes.AUD(rbsp_payload, self.verbose)
  File "/usr/local/lib/python3.7/site-packages/h26x_extractor-0.3-py3.7.egg/h26x_extractor/nalutypes.py", line 120, in __init__
    self.primary_pic_type = self.s.read('uint:3')
  File "/usr/lib/python3.7/site-packages/bitstring.py", line 3902, in read
    value, self._pos = self._readtoken(name, self._pos, length)
  File "/usr/lib/python3.7/site-packages/bitstring.py", line 2016, in _readtoken
    "Tried to read {0} bits when only {1} available.".format(int(length), self.length - pos))
bitstring.ReadError: Reading off the end of the data. Tried to read 3 bits when only 0 available.

----------------------------------------------------------------------
Ran 1 test in 0.003s

FAILED (errors=1)
```

After the AUD fix patch:

```
$ ./tests/simple_parsing.py

========================================================================================================

NALU bytepos: [0, 5]
NALU offset:  0 Bytes
NALU length:  6 Bytes (including start code)
NALU type:  9 (Access unit delimiter)
NALU bytes: 0x000000010910
NALU RBSP:  0x10

AUD (payload size: 1.0 Bytes)
+------------------+---------+
| field            |   value |
+==================+=========+
| primary_pic_type |       0 |
+------------------+---------+
.
----------------------------------------------------------------------
Ran 1 test in 0.001s

OK
```

* h26x_extractor: fix offset-by-1 in NALU parser

Tested:

Before the AUD fix patch:

```
$ ./tests/simple_parsing.py

========================================================================================================

NALU bytepos: [0, 5]
NALU offset:  0 Bytes
NALU length:  6 Bytes (including start code)
NALU type:  9 (Access unit delimiter)
NALU bytes: 0x000000010910
NALU RBSP:

E
======================================================================
ERROR: testAUDParser (__main__.ParsingTest)
Simple AUD parsing.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./tests/simple_parsing.py", line 17, in testAUDParser
    ex.parse()
  File "/usr/local/lib/python3.7/site-packages/h26x_extractor-0.3-py3.7.egg/h26x_extractor/h26x_parser.py", line 209, in parse
    aud = nalutypes.AUD(rbsp_payload, self.verbose)
  File "/usr/local/lib/python3.7/site-packages/h26x_extractor-0.3-py3.7.egg/h26x_extractor/nalutypes.py", line 120, in __init__
    self.primary_pic_type = self.s.read('uint:3')
  File "/usr/lib/python3.7/site-packages/bitstring.py", line 3902, in read
    value, self._pos = self._readtoken(name, self._pos, length)
  File "/usr/lib/python3.7/site-packages/bitstring.py", line 2016, in _readtoken
    "Tried to read {0} bits when only {1} available.".format(int(length), self.length - pos))
bitstring.ReadError: Reading off the end of the data. Tried to read 3 bits when only 0 available.

----------------------------------------------------------------------
Ran 1 test in 0.003s

FAILED (errors=1)
```

After the AUD fix patch:

```
$ ./tests/simple_parsing.py

========================================================================================================

NALU bytepos: [0, 5]
NALU offset:  0 Bytes
NALU length:  6 Bytes (including start code)
NALU type:  9 (Access unit delimiter)
NALU bytes: 0x000000010910
NALU RBSP:  0x10

AUD (payload size: 1.0 Bytes)
+------------------+---------+
| field            |   value |
+==================+=========+
| primary_pic_type |       0 |
+------------------+---------+
.
----------------------------------------------------------------------
Ran 1 test in 0.001s

OK
```